-- CyberNet AI: accounts, plans, daily limits, scan history, and Stripe links
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  plan text not null default 'free',
  subscription_status text not null default 'inactive',
  billing_interval text not null default '',
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists full_name text not null default '',
  add column if not exists plan text not null default 'free',
  add column if not exists subscription_status text not null default 'inactive',
  add column if not exists billing_interval text not null default '',
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists profiles_stripe_customer_unique
  on public.profiles (stripe_customer_id)
  where stripe_customer_id is not null;

create unique index if not exists profiles_stripe_subscription_unique
  on public.profiles (stripe_subscription_id)
  where stripe_subscription_id is not null;

create table if not exists public.daily_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null default current_date,
  analysis_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  analysis_type text not null,
  verdict text not null default 'inconclusive',
  score integer not null default 0,
  threat_type text not null default 'Security analysis',
  summary text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists scan_history_user_created_idx
  on public.scan_history (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.daily_usage enable row level security;
alter table public.scan_history enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.daily_usage from anon, authenticated;
revoke all on public.scan_history from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.daily_usage to authenticated;
grant select on public.scan_history to authenticated;

drop policy if exists "Users can read their own profile"
  on public.profiles;

create policy "Users can read their own profile"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "Users can read their own daily usage"
  on public.daily_usage;

create policy "Users can read their own daily usage"
  on public.daily_usage
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own scan history"
  on public.scan_history;

create policy "Users can read their own scan history"
  on public.scan_history
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    full_name,
    plan,
    subscription_status
  )
  values (
    new.id,
    coalesce(
      nullif(
        trim(
          concat_ws(
            ' ',
            new.raw_user_meta_data ->> 'first_name',
            new.raw_user_meta_data ->> 'last_name'
          )
        ),
        ''
      ),
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, 'User'), '@', 1)
    ),
    'free',
    'inactive'
  )
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created
  on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute procedure public.handle_new_user();

-- Add profiles for users who already existed before the trigger.
insert into public.profiles (
  id,
  full_name,
  plan,
  subscription_status
)
select
  users.id,
  coalesce(
    nullif(users.raw_user_meta_data ->> 'full_name', ''),
    split_part(coalesce(users.email, 'User'), '@', 1)
  ),
  'free',
  'inactive'
from auth.users as users
on conflict (id) do nothing;

create or replace function public.consume_analysis(
  p_user_id uuid
)
returns table (
  allowed boolean,
  used integer,
  daily_limit integer,
  plan text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan text := 'free';
  v_status text := 'inactive';
  v_limit integer := 5;
  v_used integer := 0;
begin
  select
    profiles.plan,
    profiles.subscription_status
  into
    v_plan,
    v_status
  from public.profiles
  where profiles.id = p_user_id;

  if
    v_plan = 'pro'
    and v_status in ('active', 'trialing')
  then
    v_limit := 50;
  else
    v_plan := 'free';
    v_limit := 5;
  end if;

  insert into public.daily_usage (
    user_id,
    usage_date,
    analysis_count
  )
  values (
    p_user_id,
    current_date,
    0
  )
  on conflict (user_id, usage_date)
  do nothing;

  update public.daily_usage
  set
    analysis_count = analysis_count + 1,
    updated_at = now()
  where
    user_id = p_user_id
    and usage_date = current_date
    and analysis_count < v_limit
  returning analysis_count
  into v_used;

  if v_used is null then
    select analysis_count
    into v_used
    from public.daily_usage
    where
      user_id = p_user_id
      and usage_date = current_date;

    return query
    select
      false,
      coalesce(v_used, 0),
      v_limit,
      v_plan;

    return;
  end if;

  return query
  select
    true,
    v_used,
    v_limit,
    v_plan;
end;
$$;

create or replace function public.refund_analysis(
  p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.daily_usage
  set
    analysis_count = greatest(analysis_count - 1, 0),
    updated_at = now()
  where
    user_id = p_user_id
    and usage_date = current_date;
end;
$$;

revoke all on function public.consume_analysis(uuid)
  from public, anon, authenticated;

revoke all on function public.refund_analysis(uuid)
  from public, anon, authenticated;

grant execute on function public.consume_analysis(uuid)
  to service_role;

grant execute on function public.refund_analysis(uuid)
  to service_role;

-- ═══════════════════════════════════════════════════════════════════
-- CyberNet AI: Recovery Mode — cases, versions, tasks, and daily quotas
-- Run this block in Supabase Dashboard -> SQL Editor (safe to re-run).
-- Recovery quotas reset at 12:00 PM Asia/Dubai, unlike the main AI
-- analysis quota above which resets at UTC midnight.
-- ═══════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

create table if not exists public.recovery_cases (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  incident_type text not null default 'other',
  region text not null default '',
  risk_level text not null default 'medium',
  urgency text not null default 'today',
  confidence integer not null default 50,
  status text not null default 'active',
  progress_percent integer not null default 0,
  current_version integer not null default 1,
  case_title text not null default 'Recovery Case',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists recovery_cases_owner_idx
  on public.recovery_cases (owner_user_id, updated_at desc);

create table if not exists public.recovery_versions (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.recovery_cases(id) on delete cascade,
  version_number integer not null,
  structured_plan jsonb not null,
  change_summary text not null default '',
  risk_level text not null default 'medium',
  progress_percent integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists recovery_versions_case_idx
  on public.recovery_versions (case_id, version_number desc);

create table if not exists public.recovery_tasks (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.recovery_cases(id) on delete cascade,
  plan_version integer not null default 1,
  task_key text not null,
  title text not null default '',
  status text not null default 'pending',
  priority text not null default 'normal',
  verification_note text not null default '',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (case_id, task_key)
);

create index if not exists recovery_tasks_case_idx
  on public.recovery_tasks (case_id);

create table if not exists public.recovery_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  window_start timestamptz not null,
  cases_created integer not null default 0,
  updates_used integer not null default 0,
  last_update_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, window_start)
);

alter table public.recovery_cases enable row level security;
alter table public.recovery_versions enable row level security;
alter table public.recovery_tasks enable row level security;
alter table public.recovery_usage enable row level security;

revoke all on public.recovery_cases from anon, authenticated;
revoke all on public.recovery_versions from anon, authenticated;
revoke all on public.recovery_tasks from anon, authenticated;
revoke all on public.recovery_usage from anon, authenticated;

grant select on public.recovery_cases to authenticated;
grant select on public.recovery_versions to authenticated;
grant select on public.recovery_tasks to authenticated;
grant select on public.recovery_usage to authenticated;

drop policy if exists "Users can read their own recovery cases"
  on public.recovery_cases;

create policy "Users can read their own recovery cases"
  on public.recovery_cases
  for select
  to authenticated
  using ((select auth.uid()) = owner_user_id);

drop policy if exists "Users can read versions of their own recovery cases"
  on public.recovery_versions;

create policy "Users can read versions of their own recovery cases"
  on public.recovery_versions
  for select
  to authenticated
  using (
    exists (
      select 1 from public.recovery_cases
      where recovery_cases.id = recovery_versions.case_id
        and recovery_cases.owner_user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can read tasks of their own recovery cases"
  on public.recovery_tasks;

create policy "Users can read tasks of their own recovery cases"
  on public.recovery_tasks
  for select
  to authenticated
  using (
    exists (
      select 1 from public.recovery_cases
      where recovery_cases.id = recovery_tasks.case_id
        and recovery_cases.owner_user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can read their own recovery usage"
  on public.recovery_usage;

create policy "Users can read their own recovery usage"
  on public.recovery_usage
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Returns the timestamptz marking the start of the current Recovery quota
-- window, aligned to 12:00 PM Asia/Dubai (per the CyberNet AI product spec).
create or replace function public.recovery_window_start()
returns timestamptz
language plpgsql
stable
as $$
declare
  v_dubai_now timestamptz := now() at time zone 'Asia/Dubai';
  v_today_noon timestamptz;
begin
  v_today_noon := (date_trunc('day', v_dubai_now) + interval '12 hours') at time zone 'Asia/Dubai';
  if v_dubai_now >= (date_trunc('day', v_dubai_now) + interval '12 hours') then
    return v_today_noon;
  else
    return v_today_noon - interval '1 day';
  end if;
end;
$$;

create or replace function public.recovery_next_reset()
returns timestamptz
language sql
stable
as $$
  select public.recovery_window_start() + interval '1 day';
$$;

-- Reserves one new Recovery case for the day. Free: 1/day, Pro: 5/day.
create or replace function public.consume_recovery_case(
  p_user_id uuid
)
returns table (
  allowed boolean,
  used integer,
  daily_limit integer,
  plan text,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan text := 'free';
  v_status text := 'inactive';
  v_limit integer := 1;
  v_used integer := 0;
  v_window timestamptz := public.recovery_window_start();
begin
  select profiles.plan, profiles.subscription_status
  into v_plan, v_status
  from public.profiles
  where profiles.id = p_user_id;

  if v_plan = 'pro' and v_status in ('active', 'trialing') then
    v_limit := 5;
  else
    v_plan := 'free';
    v_limit := 1;
  end if;

  insert into public.recovery_usage (user_id, window_start, cases_created, updates_used)
  values (p_user_id, v_window, 0, 0)
  on conflict (user_id, window_start) do nothing;

  update public.recovery_usage
  set cases_created = cases_created + 1, updated_at = now()
  where user_id = p_user_id
    and window_start = v_window
    and cases_created < v_limit
  returning cases_created
  into v_used;

  if v_used is null then
    select cases_created into v_used
    from public.recovery_usage
    where user_id = p_user_id and window_start = v_window;

    return query select false, coalesce(v_used, 0), v_limit, v_plan, public.recovery_next_reset();
    return;
  end if;

  return query select true, v_used, v_limit, v_plan, public.recovery_next_reset();
end;
$$;

-- Reserves one Recovery update for a specific case, enforcing both the
-- daily update limit and the per-plan cooldown between updates.
-- Free: 3/day, 6h cooldown. Pro: 12/day, 2h cooldown.
create or replace function public.consume_recovery_update(
  p_user_id uuid
)
returns table (
  allowed boolean,
  used integer,
  daily_limit integer,
  plan text,
  reset_at timestamptz,
  cooldown_seconds_remaining integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan text := 'free';
  v_status text := 'inactive';
  v_limit integer := 3;
  v_cooldown interval := interval '6 hours';
  v_used integer := 0;
  v_window timestamptz := public.recovery_window_start();
  v_last_update timestamptz;
  v_cooldown_remaining integer := 0;
begin
  select profiles.plan, profiles.subscription_status
  into v_plan, v_status
  from public.profiles
  where profiles.id = p_user_id;

  if v_plan = 'pro' and v_status in ('active', 'trialing') then
    v_limit := 12;
    v_cooldown := interval '2 hours';
  else
    v_plan := 'free';
    v_limit := 3;
    v_cooldown := interval '6 hours';
  end if;

  select last_update_at into v_last_update
  from public.recovery_usage
  where user_id = p_user_id and window_start = v_window;

  if v_last_update is not null and now() < v_last_update + v_cooldown then
    v_cooldown_remaining := ceil(extract(epoch from ((v_last_update + v_cooldown) - now())));
    select updates_used into v_used
    from public.recovery_usage
    where user_id = p_user_id and window_start = v_window;

    return query select false, coalesce(v_used, 0), v_limit, v_plan, public.recovery_next_reset(), greatest(0, v_cooldown_remaining);
    return;
  end if;

  insert into public.recovery_usage (user_id, window_start, cases_created, updates_used)
  values (p_user_id, v_window, 0, 0)
  on conflict (user_id, window_start) do nothing;

  update public.recovery_usage
  set updates_used = updates_used + 1, last_update_at = now(), updated_at = now()
  where user_id = p_user_id
    and window_start = v_window
    and updates_used < v_limit
  returning updates_used
  into v_used;

  if v_used is null then
    select updates_used into v_used
    from public.recovery_usage
    where user_id = p_user_id and window_start = v_window;

    return query select false, coalesce(v_used, 0), v_limit, v_plan, public.recovery_next_reset(), 0;
    return;
  end if;

  return query select true, v_used, v_limit, v_plan, public.recovery_next_reset(), 0;
end;
$$;

revoke all on function public.consume_recovery_case(uuid) from public, anon, authenticated;
revoke all on function public.consume_recovery_update(uuid) from public, anon, authenticated;
revoke all on function public.recovery_window_start() from public, anon, authenticated;
revoke all on function public.recovery_next_reset() from public, anon, authenticated;

grant execute on function public.consume_recovery_case(uuid) to service_role;
grant execute on function public.consume_recovery_update(uuid) to service_role;
grant execute on function public.recovery_window_start() to service_role, authenticated;
grant execute on function public.recovery_next_reset() to service_role, authenticated;

-- ═══════════════════════════════════════════════════════════════════
-- CyberNet AI: Legal acceptance records (Terms/Privacy/Acceptable Use/
-- Refund policy acceptance at signup and checkout).
-- Previously shipped as a separate file (legal_privacy_upgrade.sql);
-- merged here so schema.sql is the single authoritative migration.
-- ═══════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

create table if not exists public.legal_acceptances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  acceptance_type text not null check (acceptance_type in ('signup','checkout','reaccept')),
  terms_version text not null,
  privacy_version text not null,
  acceptable_use_version text not null,
  refund_version text not null,
  billing_cycle text check (billing_cycle is null or billing_cycle in ('monthly','yearly')),
  accepted_at timestamptz not null default now(),
  page_url text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists legal_acceptances_user_created_idx
  on public.legal_acceptances (user_id, created_at desc);

alter table public.legal_acceptances enable row level security;
revoke all on public.legal_acceptances from anon, authenticated;
grant select on public.legal_acceptances to authenticated;

-- Users can view only their own acceptance history. Inserts are performed only
-- by the authenticated Netlify Function using the Supabase service-role key.
drop policy if exists "Users can read their own legal acceptances" on public.legal_acceptances;
create policy "Users can read their own legal acceptances"
  on public.legal_acceptances for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- ═══════════════════════════════════════════════════════════════════
-- CyberNet AI: Public platform stats (for the Home page "Live Activity"
-- panel). Returns real aggregate counts only — no per-user data, no PII.
-- Called by netlify/functions/public-stats.mts using the service-role
-- key; never exposed to anon/authenticated roles directly.
-- ═══════════════════════════════════════════════════════════════════

create or replace function public.get_platform_stats()
returns table (
  total_scans bigint,
  threats_found bigint,
  recovery_cases bigint
)
language sql
security definer
set search_path = public
stable
as $$
  select
    (select coalesce(sum(analysis_count), 0) from public.daily_usage) as total_scans,
    (select count(*) from public.scan_history where verdict in ('malicious', 'suspicious')) as threats_found,
    (select count(*) from public.recovery_cases) as recovery_cases;
$$;

revoke all on function public.get_platform_stats() from public, anon, authenticated;
grant execute on function public.get_platform_stats() to service_role;
