// Business email and chat fraud (BEC): CEO fraud, invoice and vendor bank-detail
// changes, payroll diversion, fake purchase orders, W-2 requests, fake
// DocuSign / SharePoint shares, Microsoft 365 password expiry, IT helpdesk MFA
// fatigue, recruiter lures — plus the genuine business messages that look
// similar and must stay NOT A SCAM. All names, numbers and domains are made up.
export const CASES = [
  // ── CEO / executive impersonation ──
  { id: "ceo-available-opener", type: "text", expect: "scam", input: "Hi, are you available? I need you to take care of something for me discreetly, I'm in a conference and can't take calls right now. Send me your personal cell number and I'll text you the details. Sent from my iPhone", note: "Classic BEC opener: no money asked yet, but 'can't take calls', 'discreetly', 'personal cell number' and 'sent from my iPhone' are the setup for a gift-card or wire ask" },
  { id: "ceo-gift-card-sms", type: "text", expect: "scam", input: "Hi its Tom (CEO). Am tied up in a mtg, need u to buy 3 gift cards for a client asap. Wil pay u back. Text me when done", note: "Short SMS with typos" },
  { id: "ceo-gift-card-obfuscated", type: "text", expect: "scam", input: "Hey, are u in the office? I need u to get 6 Apple g1ft cards ($100 each) for staff rewards asap and text me the c0des. Am in a meeting, cant talk. Sent from my iPhone", note: "1 for i and 0 for o in 'gift cards' and 'codes'; verbs 'get' and 'text me' instead of 'buy' / 'send me'" },
  { id: "ceo-vouchers-email-codes", type: "text", expect: "scam", input: "Hi, can you do me a favour? Purchase 4 Amazon vouchers of £250 each from the shop downstairs and email me the codes on the back. I'll reimburse you this afternoon. In meetings all day, don't call.", note: "'vouchers' instead of 'gift cards'" },
  { id: "ceo-wire-confidential", type: "text", expect: "scam", input: "Hi Dana, I need you to process a wire transfer of $48,500 to a new vendor today for the acquisition. This is confidential, please do not discuss it with anyone in the office. Bank details are attached. I'll be in board meetings all day so email is best.", note: "CEO wire fraud: 'this is confidential' + 'do not discuss' + 'email is best', but no word from the urgency or secrecy term lists" },
  { id: "ceo-wire-urgent-secret", type: "text", expect: "scam", input: "Urgent: I need a wire transfer of EUR 19,750 sent to the supplier below before 3 pm today to close the deal. Keep this confidential until it's announced. I'm travelling and can't take calls, reply by email." },
  { id: "arabic-ceo-gift-cards", type: "text", expect: "scam", input: "مرحباً، أنا المدير العام. أحتاج منك شراء بطاقات هدايا آبل بقيمة 500 دولار لعملاء مهمين وإرسال الأكواد لي الآن. أنا في اجتماع ولا أستطيع الرد على الهاتف. لا تخبر أحداً في المكتب.", note: "Arabic CEO gift-card fraud: buy Apple gift cards, send me the codes now, in a meeting, tell nobody" },
  { id: "w2-request-ceo", type: "text", expect: "scam", input: "Hi, it's Robert. I'm reviewing staff records with the auditors this morning and need the 2025 W-2 forms for all employees as a single PDF. Can you send them over to me as soon as you get this? Thanks, sent from my mobile", note: "W-2 / tax-form phishing: an executive asking payroll to email every employee's tax form" },

  // ── Invoice fraud / vendor bank-detail changes ──
  { id: "invoice-remittance-account-changed", type: "text", expect: "scam", input: "Please be advised that our remittance account has changed with effect from 1 October. Kindly update your vendor records and remit all outstanding invoices to the new account: Bank of Sample plc, Account No. 55501234, Sort code 20-00-00. Regards, Accounts Receivable", note: "'remittance account has changed' / 'the new account' instead of 'bank details' or 'IBAN'" },
  { id: "vendor-iban-updated", type: "text", expect: "scam", input: "Dear valued partner, kindly note that our IBAN has been updated for all future payments. New IBAN: AE07 0331 2345 6789 0123 456. Please use it for invoice 2291 due next week. Regards, Accounts Receivable" },
  { id: "vendor-banking-details-www-link", type: "text", expect: "scam", input: "Notice: our banking details have changed. Updated remittance instructions are on our portal: www.vendor-payments-update.com/remit. Please pay invoice 3310 to the new account.", note: "'banking details have changed' (noun before verb, 'banking' not 'bank') and a www. link with no scheme" },
  { id: "vendor-details-obfuscated", type: "text", expect: "scam", input: "Please note our bank detai1s have changed. Kindly send all future payments to the new acc0unt below and confirm once updated. Acc0unt name: Northline Supplies Ltd, Acc0unt no: 44019921, Sort code 30-12-77.", note: "1 for l and 0 for o inside 'details' and 'account' to dodge filters" },
  { id: "vendor-iban-arabic-nocall", type: "text", expect: "scam", input: "تحية طيبة، نود إبلاغكم بأن رقم الآيبان الخاص بشركتنا قد تغير. يرجى تحويل قيمة الفاتورة رقم 4471 إلى الحساب الجديد أدناه. لا تتصل بي، أنا في اجتماع طوال اليوم." },
  { id: "invoice-enable-content-macro", type: "text", expect: "scam", input: "Please see attached invoice INV-20931 for your records. This document is protected; open it in Microsoft Word, click Enable Editing and then Enable Content to view it.", note: "Macro-malware lure: 'Enable Editing' / 'Enable Content' is how the attachment runs code" },
  { id: "fake-po-gmail-procurement", type: "text", expect: "scam", input: "Good day, please find attached Purchase Order PO-77812 for immediate processing. Kindly acknowledge receipt and send the proforma invoice to our procurement office at procurement-global-supplies@gmail.com. Payment will be made by wire transfer 30 days after delivery. Regards, Procurement Department", note: "Fake purchase order: a 'Procurement Department' using a free Gmail address, goods shipped on credit" },

  // ── Payroll / direct-deposit diversion ──
  { id: "payroll-direct-deposit-change", type: "text", expect: "scam", input: "Hi, I'd like to change my direct deposit account before the next payroll run. My new routing number is 021000021 and account number 88812345. Can you update it today? I no longer have access to my old account. Thanks, Priya", note: "Payroll diversion sent to HR from a look-alike employee address" },
  { id: "payroll-new-bank-details-attached", type: "text", expect: "scam", input: "Hello HR, I've switched banks so please update my salary payment to the new bank details attached before Friday's payroll run. Let me know if you need anything else. Thanks, Omar" },

  // ── Fake document shares, password expiry, MFA fatigue, recruiter lure ──
  { id: "docusign-fake-text", type: "text", expect: "scam", input: "DocuSign - Completed: Please review and sign your document. 'Contract-Agreement-2026.pdf' is waiting for your signature. Review document: http://docusign-review-secure.online/sign?id=8812", note: "The link alone scores as a scam; the same link inside the message should not score lower" },
  { id: "sharepoint-fake-share", type: "text", expect: "scam", input: "Layla shared a file with you: 'Q3 Payment Schedule.xlsx'. Open in SharePoint: https://sharepoint-docs-share.com/open/file?doc=Q3", note: "SharePoint share notice pointing at a domain that is not sharepoint.com" },
  { id: "office365-password-expiry", type: "text", expect: "scam", input: "Your Office 365 password will expire in 24 hours. To keep your current password, verify here: https://office365-password-keep.com/auth?user=finance", note: "'expire in 24 hours' rather than 'within 24 hours'; 'Office 365' rather than 'Microsoft'" },
  { id: "m365-password-expiry-brand", type: "text", expect: "scam", input: "Microsoft 365: your password expires today. Verify your account now to keep your current password or you will lose access to your mailbox: https://microsoft365-verify-login.com/auth" },
  { id: "it-helpdesk-mfa-approve", type: "text", expect: "scam", input: "IT Helpdesk: we've detected repeated sign-in attempts on your account from an unknown device. Please approve the Microsoft Authenticator prompt we just sent to your phone so we can secure your session. Approve it within the next 10 minutes or the sync will fail.", note: "MFA fatigue: asking the victim to approve a push prompt the attacker triggered" },
  { id: "linkedin-recruiter-onboarding", type: "text", expect: "scam", input: "Hi! I came across your profile on LinkedIn and think you'd be a great fit for a remote Data Entry role at our company, $45/hr with flexible hours. To proceed, please complete the onboarding form and upload a copy of your ID and your bank details for payroll setup: https://hr-onboarding-forms.net/apply", note: "Recruiter lure asking for ID and bank details before any interview" },

  // ── Links ──
  { id: "link-docusign-fake", type: "link", expect: "scam", input: "http://docusign-review-secure.online/sign?id=8812" },
  { id: "link-po-zip", type: "link", expect: "scam", input: "http://purchase-order-docs.com/PO-77812.zip" },
  { id: "link-m365-lookalike", type: "link", expect: "scam", input: "https://login-microsoft365-portal.com/owa" },
  { id: "link-sharepoint-unknown", type: "link", expect: "scam", input: "https://sharepoint-docs-share.com/open/file?doc=Q3", note: "Nothing structurally wrong with the bare address; only the message around it gives it away" },
  { id: "link-office-official", type: "link", expect: "safe", input: "https://outlook.office.com/mail/inbox", note: "Microsoft's real Office web mail domain" },
  { id: "link-linkedin-official", type: "link", expect: "safe", input: "https://www.linkedin.com/jobs/view/4123456" },

  // ── Legitimate business messages that must stay NOT A SCAM ──
  { id: "safe-bank-change-invites-call", type: "text", expect: "safe", input: "Hi Jonathan, as discussed on the call yesterday, our bank details have changed following our move to a new bank. The updated details are in the attached letter on our letterhead. Please call me on the usual office number to confirm before you make the next payment.", note: "A genuine change invites a phone check on a number the reader already has" },
  { id: "safe-invoice-payable-within-30-days", type: "text", expect: "safe", input: "Good afternoon, attached is invoice 2026-118 for the consulting work in August, total EUR 3,200, payable within 30 days to the account shown on the invoice as usual. Let me know if you need a PO number. Best regards, Hana", note: "'payable within 30 days' is standard payment-terms wording" },
  { id: "safe-calendar-invite", type: "text", expect: "safe", input: "Invitation: Q4 planning review @ Thu 2 Oct 2026 10:00 - 11:00 (GST). Join Microsoft Teams meeting. Organizer: Layla. Accept / Tentative / Decline" },
  { id: "safe-supplier-overdue-polite", type: "text", expect: "safe", input: "Hello, a gentle reminder that the outstanding balance of AED 4,800 on invoice 5520 is now overdue. Could you let us know when we can expect payment? Happy to resend the invoice if it helps. Kind regards, Accounts team" },
  { id: "safe-it-password-policy", type: "text", expect: "safe", input: "IT notice: from 1 October, passwords must be at least 14 characters and will expire every 180 days. Windows will remind you 7 days before expiry. No action is needed now. IT will never ask you for your password by email or phone." },
  { id: "safe-hr-payroll-dates", type: "text", expect: "safe", input: "HR update: September salaries will be paid on Thursday 25 September. Payslips will be available in the HR portal the day before. Questions to your usual HR contact." },
  { id: "safe-customer-complaint", type: "text", expect: "safe", input: "I'm writing to complain about order 77120. The delivery arrived two weeks late and the invoice charged me twice for shipping. I'd like a refund of the duplicate charge. Please respond within 5 working days." },
  { id: "safe-contract-for-review", type: "text", expect: "safe", input: "Hi, attached is the draft services agreement for your review. Key changes are in section 4 (payment terms: net 45) and section 9 (liability cap). Please send your comments by the end of next week and we can set up a call." },
  { id: "safe-sharepoint-real-share", type: "text", expect: "safe", input: "Omar shared 'Board deck v3.pptx' with you. Open: https://contoso.sharepoint.com/sites/finance/Shared%20Documents/board-deck-v3.pptx" },
  { id: "safe-boss-are-you-free", type: "text", expect: "safe", input: "Hi Sam, are you free for 10 minutes this afternoon? Want to go over the budget slides before Thursday's board meeting. My calendar is up to date, grab any slot." },
  { id: "safe-it-mfa-rollout", type: "text", expect: "safe", input: "Reminder: multi-factor authentication becomes mandatory for all staff on 15 October. Set it up from Settings > Security in your account before then. IT will run drop-in sessions on Tuesday. No links are needed, and we will never ask for your password." },
  { id: "safe-vendor-onboarding-w9", type: "text", expect: "safe", input: "Welcome aboard as a supplier. Before we can pay your first invoice, our AP team needs a completed W-9 and a certificate of insurance. Please upload them through the vendor portal you registered on, not by email." },
  { id: "safe-recruiter-intro", type: "text", expect: "safe", input: "Hi, I'm a recruiter at a fintech in Dubai. Your background in data engineering looks like a strong match for a senior role we're hiring for. If you're open to it, happy to share the job description and set up a 20-minute intro call next week." },
  { id: "safe-arabic-invoice", type: "text", expect: "safe", input: "مرحباً فريق المحاسبة، مرفق فاتورة شهر أغسطس رقم 2210 بقيمة 12,500 درهم حسب العقد. شروط الدفع 30 يوماً كالمعتاد. شكراً لتعاونكم" },
  { id: "safe-hr-bank-change-reminder", type: "text", expect: "safe", input: "Payroll reminder: if you need to change the bank account your salary is paid into, do it yourself in the HR self-service portal. HR will never change bank details based on an email request." },
];
