-- CyberNet AI: accounts, plans, secure daily limits, and Pro scan history
-- Run this entire file once in Supabase Dashboard -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  plan text not null default 'free' check (plan in ('free', 'pro')),
  subscription_status text not null default 'inactive',
  billing_interval text not null default '',
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null default current_date,
  analysis_count integer not null default 0 check (analysis_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  analysis_type text not null check (analysis_type in ('text', 'link', 'image')),
  verdict text not null default 'inconclusive',
  score integer not null default 0 check (score between 0 and 100),
  threat_type text not null default 'Security analysis',
  summary text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists scan_history_user_created_idx
  on public.scan_history (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.daily_usage enable row level security;
alter table public.scan_history enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.daily_usage from anon, authenticated;
revoke all on public.scan_history from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.daily_usage to authenticated;
grant select on public.scan_history to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "Users can read their own daily usage" on public.daily_usage;
create policy "Users can read their own daily usage"
  on public.daily_usage for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own scan history" on public.scan_history;
create policy "Users can read their own scan history"
  on public.scan_history for select to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, plan, subscription_status)
  values (
    new.id,
    coalesce(
      nullif(trim(concat_ws(' ', new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data ->> 'last_name')), ''),
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, 'User'), '@', 1)
    ),
    'free',
    'inactive'
  )
  on conflict (id) do update
  set full_name = excluded.full_name, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.consume_analysis(p_user_id uuid)
returns table (allowed boolean, used integer, daily_limit integer, plan text)
language plpgsql
security definer set search_path = public
as $$
declare
  v_plan text := 'free';
  v_status text := 'inactive';
  v_limit integer := 5;
  v_used integer := 0;
begin
  select p.plan, p.subscription_status into v_plan, v_status
  from public.profiles p where p.id = p_user_id;

  if v_plan = 'pro' and v_status in ('active', 'trialing') then
    v_limit := 50;
  else
    v_plan := 'free';
    v_limit := 5;
  end if;

  insert into public.daily_usage (user_id, usage_date, analysis_count)
  values (p_user_id, current_date, 0)
  on conflict (user_id, usage_date) do nothing;

  update public.daily_usage
  set analysis_count = analysis_count + 1, updated_at = now()
  where user_id = p_user_id and usage_date = current_date and analysis_count < v_limit
  returning analysis_count into v_used;

  if v_used is null then
    select analysis_count into v_used from public.daily_usage
    where user_id = p_user_id and usage_date = current_date;
    return query select false, coalesce(v_used, 0), v_limit, v_plan;
  end if;

  return query select true, v_used, v_limit, v_plan;
end;
$$;

create or replace function public.refund_analysis(p_user_id uuid)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  update public.daily_usage
  set analysis_count = greatest(analysis_count - 1, 0), updated_at = now()
  where user_id = p_user_id and usage_date = current_date;
end;
$$;

revoke all on function public.consume_analysis(uuid) from public, anon, authenticated;
revoke all on function public.refund_analysis(uuid) from public, anon, authenticated;
grant execute on function public.consume_analysis(uuid) to service_role;
grant execute on function public.refund_analysis(uuid) to service_role;